version: '3.3'
services:
  db:
    image: mysql:5.7
    container_name: my-sql-railway
    restart: always
    environment:
      MYSQL_DATABASE: 'db_crudrailway'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'root'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'root'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3305:3306'
    volumes:
      - ./.data/dbmysql/data:/var/lib/mysql
    networks:
      - fern-network




#mysql://root:D6A3BE-b1e25c6BHDc3-B2FDfdG-GBAC@viaduct.proxy.rlwy.net:15751/railway
#jdbc:mysql://viaduct.proxy.rlwy.net:15751/railway